### ISSUE TITLE
Javascript error using fastplotlib modules in jlab_caiman and jlab_caiman-workshop23 containers

### ISSUE THREAD

**Issue by vncntprvst** [wanglab-neuro/jupyterlab_containers#1]
In `fpl-demos` / `simple` notebook, executing the cell with the following code:
```
# create a `Plot` instance
plot = Plot()
# make some random 2D image data
data = np.random.rand(512, 512)
# plot the image data
image_graphic = plot.add_image(data=data, name="random-image")
# show the plot
plot.show()
```
returns this error:
```
Failed to load model class 'RemoteFrameBufferModel' from module 'jupyter_rfb'
loadClass@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:74856
loadModelClass@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:10729
_make_model@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:7517
new_model@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:5137
handle_comm_open@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:3894
134/v/this._handleCommOpen@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:73393
_handleCommOpen@http://127.0.0.1:8888/static/lab/jlab_core.d6bc082464b66ab0e79a.js?v=d6bc082464b66ab0e79a:2:994480
```
Here's how the error looks like:
![image](https://user-images.githubusercontent.com/1872756/221929491-6a4af748-5115-4548-9575-f4b1d3aa3b08.png)

Similarly, in `cnmf` / `workshop_cnmf_demo` notebook, executing this code:
```
iw = ImageWidget(
    data=m_orig, 
    slider_dims=["t"],
    vmin_vmax_sliders=True,
    cmap="gray")
iw.show()
```
returns this error: 
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'VBoxModel' from module '@jupyter-widgets/controls'
loadClass@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:74977
loadModelClass@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:10729
_make_model@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:7517
new_model@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:5137
handle_comm_open@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:3894
134/v/this._handleCommOpen@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1:73393
_handleCommOpen@http://127.0.0.1:8888/static/lab/jlab_core.d6bc082464b66ab0e79a.js?v=d6bc082464b66ab0e79a:2:994480
```

All other code seem to work fine (e.g., CaImAn's demo pipeline)

**Comment by vncntprvst** [comment]
It may be related to [that issue](https://stackoverflow.com/questions/73715821/jupyter-lab-issue-displaying-widgets-javascript-error).   
The installed `ipywidgets` version is  `8.0.2              pyhd8ed1ab_1    conda-forge`.  
I can test other versions.

**Comment by vncntprvst** [comment]
Tested with `ipywidgets` `8.0.4` and `7.7.2`, as well as `ipympl` `0.9.3`. Same error.

**Comment by kushalkolar** [comment]
You will need to use the latest version of `jupyter_rfb`, v0.3.3

**Comment by vncntprvst** [comment]
Ok, some progress. I first followed [this fix](https://github.com/matplotlib/ipympl/issues/460#issuecomment-1382993578), and made sure `jupyter_rfb` version was v0.3.3. I got a plot, but followed by the same error.
![image](https://user-images.githubusercontent.com/1872756/222012568-49d9e329-8210-4c14-96c3-4f82304fc9e7.png)

Then I rebuilt a container with an updated Dockerfile, and now I'm seeing this error after the "Simple image" code cell: 
```
Model class 'RemoteFrameBufferModel' from module 'jupyter_rfb' is loaded but can not be instantiated
_make_model@http://127.0.0.1:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1:7933
```
TBC

**Comment by kushalkolar** [comment]
what version of `jupyterlab-widgets`? Try with the latest ipywidgets, jupyterlab-widgets, and jupyter_rfb

**Comment by kushalkolar** [comment]
There were a number of breaking changes when ipywidgets moved from v7 to v8, you could try to build with:

```
jupyterlab-widgets==1.1.1
ipywidgets<8.0.0
jupyter_rfb==0.3.2
```

**Comment by vncntprvst** [comment]
The package versions were: 
```
    jupyter-rfb               0.3.3                    pypi_0    pypi
    jupyterlab-widgets        1.1.1                    pypi_0    pypi
    ipywidgets                7.7.3                    pypi_0    pypi
```
I uninstalled and re-installed, tested both with conda and pip. I'm still getting this: 
![image](https://user-images.githubusercontent.com/1872756/222186009-153153e3-5e98-4e89-a172-1b47201ca60f.png)
I'll get back to it later today. 
Thanks for the help!

**Comment by vncntprvst** [comment]
Just a quick note: as `jupyter_rfb` seems to be developed with Node.js, I wonder if to use it in a container one would need to map specific resources. See e.g. [this thread](https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds). I guess I can ask the devs what they think.

**Comment by vncntprvst** [comment]
Fixed this with installing packages in base environment. Tested on `jupyter/tensorflow-notebook:lab-3.5.3` container with no requirement for Python or `ipywidgets`. Just installed `fastplotlib` before `mesmerize`:
```
RUN pip install fastplotlib
RUN conda install -y -c conda-forge mesmerize-core
```
See more detailed comment [here](https://github.com/vispy/jupyter_rfb/issues/68#issuecomment-1452498089).

**Comment by vncntprvst** [comment]
Tested and working on jupyterhub with `tensorflow-notebook:hub-3.1.1` base.

**Comment by tkmymgc** [comment]
I had the same issue using Chrome on windows. Using Internet explorer (Microsoft Edge) solved the issue. Refer to https://requirejs.org/docs/errors.html#scripterror
